/**
 * Stamp was generated by <generateFileStamps.sh>
 * Last time was modified by <StampedSourceFile.kt>
 *
 * Created: <02/07/2020, 11:27:00 PM>
 * Modified: <04/07/2020, 10:57:25 PM>
 * Version: <2>
 */

package worder.model.insert.request

import worder.core.model.Word


interface Requester {
//    val sessionStat: RequesterSessionStat
//        get() = throw IllegalStateException("Should be used RequesterStatDecorator() implementation!")
//
//    val lastRequestStat: RequestStat
//        get() = throw IllegalStateException("Should be used RequesterStatDecorator() implementation!")


    suspend fun requestWord(word: Word)
}


interface DefinitionRequester : Requester {
    val definitions: Set<String>
}

interface TranslationRequester : Requester {
    val translations: Set<String>
}

interface ExampleRequester : Requester {
    val examples: Set<String>
}

interface TranscriptionRequester : Requester {
    val transcriptions: Set<String>
}
