/**
 * Stamp was generated by <StampedFile.kt>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <TeeOutputStream.java>
 * Created: <12/11/2020, 03:39:25 PM>
 * Modified: <14/11/2020, 09:32:54 PM>
 * Version: <163>
 */

package worder.launcher.logging;

import java.io.IOException;
import java.io.OutputStream;

public class TeeOutputStream extends OutputStream {
    private final OutputStream[] streams;


    public TeeOutputStream(OutputStream... streams) {
        this.streams = streams;
    }


    @Override
    public void write(int b) throws IOException {
        for (OutputStream stream : streams) {
            stream.write(b);
        }
    }

    @SuppressWarnings("NullableProblems")
    @Override
    public void write(byte[] b) throws IOException {
        for (OutputStream stream : streams) {
            stream.write(b);
        }
    }

    @SuppressWarnings("NullableProblems")
    @Override
    public void write( byte[] b, int off, int len) throws IOException {
        for (OutputStream stream : streams) {
            stream.write(b, off, len);
        }
    }

    @Override
    public void close() throws IOException {
        for (OutputStream stream : streams) {
            stream.close();
        }
    }

    @Override
    public void flush() throws IOException {
        for (OutputStream stream : streams) {
            stream.flush();
        }
    }
}
