package worder

import io.kotest.core.spec.style.ShouldSpec
import io.kotest.matchers.collections.containNull
import io.kotest.matchers.collections.containOnlyNulls
import io.kotest.matchers.should
import io.kotest.matchers.shouldNot
import io.kotest.matchers.shouldNotBe
import java.io.File
import java.nio.file.Path

class StampedSourceFileTest : ShouldSpec({
    val validStamp = """
            /**
             * This stamp was generated by <generateFileStamps.sh> at <Sat Jun 27 23:02:07 2020>
             * Last time was checked by <generateFileStamps.sh> at <Sat Jun 27 23:02:07 2020>
             *
             * Created: <Sat Jun 27 22:51:50 2020>
             * Modified: <Wed Jun 24 17:27:24 2020>
             * Version: #<1>
             */

            package worder.core.model

            import javafx.scene.paint.Paint

            interface Status {
                val description: String
                val color: Paint
            }

        """.trimIndent()
    val invalidStamp = """
            /**
             * My comment OOPs
             * Last time was checked by <generateFileStamps.sh> at <Sat Jun 27 23:02:07 2020>
             *
             * Created: <Sat Jun 27 22:51:50 2020>
             * Modified: <Wed Jun 24 17:27:24 2020>
             * Version: #<1>
             */

            package worder.core.model

            import javafx.scene.paint.Paint

            interface Status {
                val description: String
                val color: Paint
            }

        """.trimIndent()
    val noStamp = """
            package worder.core.model

            import javafx.scene.paint.Paint

            interface Status {
                val description: String
                val color: Paint
            }

        """.trimIndent()

    val testDir = Path.of("build", "tests", "SourceFileStampTest").toFile().also {
        if (!it.exists())
            it.mkdirs()
    }
    val validStampFiles = listOf(
            testDir.resolve("validStamp.kt").also { it.writeText(validStamp) },
            testDir.resolve("validStamp.kts").also { it.writeText(validStamp) }
    )
    val invalidStampFiles = listOf(
            testDir.resolve("invalidStamp.kt").also { it.writeText(invalidStamp) },
            testDir.resolve("invalidStamp.kts").also { it.writeText(invalidStamp) }
    )
    val noStampFiles = listOf(
            testDir.resolve("noStamp.kt").also { it.writeText(noStamp) },
            testDir.resolve("noStamp.kts").also { it.writeText(noStamp) }
    )


    xshould("work with valid stamp") {
        validStampFiles.map { StampedSourceFile.fromFile(it) } shouldNot containNull()
    }

    xshould("work with files with no stamp") {
        noStampFiles.map { StampedSourceFile.fromFile(it) } shouldNot containNull()
    }

    xshould("not work with invalid stamp") {
        invalidStampFiles.map { StampedSourceFile.fromFile(it) } should containOnlyNulls()
    }

    should("retrieve file's creation date") {
        val stampedFile = StampedSourceFile.fromFile(File("build.gradle.kts"))
        stampedFile shouldNotBe null

        stampedFile!!.obtainFileCreationTime()
    }
})
