/**
 * Stamp was generated by <generateFileStamps.sh>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <UpdateTabView.kt>
 * Created: <02/07/2020, 11:27:00 PM>
 * Modified: <24/07/2020, 07:46:58 PM>
 * Version: <9>
 */

package worder.update

import javafx.scene.Parent
import tornadofx.View
import tornadofx.stackpane
import worder.database.DatabaseController
import worder.database.DatabaseEventListener
import worder.database.model.WorderDB
import worder.database.ui.NoConnectionFragment
import worder.tornadofx.replaceChildren
import worder.update.ui.WordsPipelineFragment

class UpdateTabView : View("Update"), DatabaseEventListener {
    private val notConnectedFragment = find<NoConnectionFragment>()


    override val root: Parent = stackpane()


    init {
        find<DatabaseController>().subscribeAndRaise(this)
    }


    override fun onDatabaseConnection(db: WorderDB) = root.replaceChildren(find<WordsPipelineFragment>("database" to db.updater))

    override fun onDatabaseDisconnection() = root.replaceChildren(notConnectedFragment)
}
