/**
 * Stamp was generated by <generateFileStamps.sh>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <UpdateView.kt>
 * Created: <02/07/2020, 11:27:00 PM>
 * Modified: <20/07/2020, 06:37:21 PM>
 * Version: <7>
 */

package worder.update

import javafx.scene.Parent
import tornadofx.View
import tornadofx.stackpane
import worder.database.DatabaseController
import worder.database.DatabaseEventListener
import worder.database.model.WorderDB
import worder.database.ui.NoConnectionFragment
import worder.tornadofx.replaceChildren
import worder.update.ui.UpdateModelFragment

class UpdateView : View("Update"), DatabaseEventListener {
    private val notConnectedFragment = find<NoConnectionFragment>()


    override val root: Parent = stackpane()


    init {
        find<DatabaseController>().subscribeAndRaise(this)
    }


    override fun onDatabaseConnection(db: WorderDB) = root.replaceChildren(find<UpdateModelFragment>("db" to db.updater))

    override fun onDatabaseDisconnection() = root.replaceChildren(notConnectedFragment)
}
