/**
 * Stamp was generated by <StampedFile.kt>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <ConsoleUI.java>
 * Created: <11/11/2020, 08:24:43 PM>
 * Modified: <11/11/2020, 08:25:17 PM>
 * Version: <2>
 */

package worder.launcher.ui.impl.console;

import worder.launcher.ui.UiHandler;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.FormatStyle;

public class ConsoleUI implements UiHandler {
    @Override
    public void show() {
    }

    @Override
    public void dispose(long delay) {
    }

    @Override
    public void status(String status) {
        System.out.printf(
                "[%s] [STATUS] %s%n",
                LocalDateTime.now().format(DateTimeFormatter.ofLocalizedDateTime(FormatStyle.MEDIUM)),
                status
        );
    }

    @Override
    public void error(String message) {
        System.out.printf(
                "[%s] [ERROR] %s%n",
                LocalDateTime.now().format(DateTimeFormatter.ofLocalizedDateTime(FormatStyle.MEDIUM)),
                message
        );
    }
}
