/**
 * Stamp was generated by <StampedFile.kt>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <App.java>
 * Created: <04/08/2020, 07:03:59 PM>
 * Modified: <28/10/2020, 10:27:32 PM>
 * Version: <168>
 */

package worder.launcher;

public class App {
    public static void main(String[] args) {
        UI UI = new UI();

        UI.updateProgress("New status 2...");
        UI.updateProgress("I've got an idea...");
        UI.updateProgress("Downloading something important1.jar...");
        UI.updateProgress("Downloading something important2.jar...");
        UI.updateProgress("Downloading something important3.jar...");
        UI.updateProgress("Starting Worder GUI...");
    }
}
