/**
 * Stamp was generated by <StampedFile.kt>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <MoveJFrame.java>
 * Created: <27/10/2020, 08:51:08 PM>
 * Modified: <27/10/2020, 09:01:15 PM>
 * Version: <12>
 */

package worder.launcher;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;

public class MoveJFrame extends JFrame {

    public MoveJFrame() {


//        this.setUndecorated(true);
//        this.setSize(500, 300);


        FrameDragListener frameDragListener = new FrameDragListener(this);
        this.addMouseListener(frameDragListener);
        this.addMouseMotionListener(frameDragListener);

//        this.pack();
//        this.setLocationRelativeTo(null);
//        this.setVisible(true);

    }

    public static class FrameDragListener extends MouseAdapter {

        private final JFrame frame;
        private Point mouseDownCompCords = null;

        public FrameDragListener(JFrame frame) {
            this.frame = frame;
        }

        public void mouseReleased(MouseEvent e) {
            mouseDownCompCords = null;
        }

        public void mousePressed(MouseEvent e) {
            mouseDownCompCords = e.getPoint();
        }

        public void mouseDragged(MouseEvent e) {
            Point currCords = e.getLocationOnScreen();
            frame.setLocation(currCords.x - mouseDownCompCords.x, currCords.y - mouseDownCompCords.y);
        }
    }
}
