/**
 * Stamp was generated by <StampedFile.kt>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <UiHandlerAggregator.java>
 * Created: <11/11/2020, 08:24:43 PM>
 * Modified: <11/11/2020, 08:25:17 PM>
 * Version: <2>
 */

package worder.launcher.ui;

public class UiHandlerAggregator implements UiHandler {
    private final UiHandler[] uiHandlers;


    public UiHandlerAggregator(UiHandler... uiHandlers) {
        this.uiHandlers = uiHandlers;
    }


    @Override
    public void show() {
        for (UiHandler uiHandler : uiHandlers) {
            uiHandler.show();
        }
    }

    @Override
    public void dispose(long delay) {
        for (UiHandler uiHandler : uiHandlers) {
            uiHandler.dispose(delay);
        }
    }

    @Override
    public void status(String status) {
        for (UiHandler uiHandler : uiHandlers) {
            uiHandler.status(status);
        }
    }

    @Override
    public void error(String message) {
        for (UiHandler uiHandler : uiHandlers) {
            uiHandler.error(message);
        }
    }
}
