/**
 * Stamp was generated by <StampedFile.kt>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <UiHandler.java>
 * Created: <05/11/2020, 08:36:34 PM>
 * Modified: <05/11/2020, 10:28:14 PM>
 * Version: <24>
 */

package worder.launcher.ui;

public interface UiHandler {
    void status(String status);
    void criticalError(String message);
}
