/**
 * Stamp was generated by <StampedFile.kt>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <UiHandler.java>
 * Created: <05/11/2020, 08:36:34 PM>
 * Modified: <11/11/2020, 10:02:10 PM>
 * Version: <177>
 */

package worder.launcher.ui;

public interface UiHandler {
    void show();

    void dispose(long delay);

    void status(String status);

    void error(String message);
}
