/**
 * Stamp was generated by <generateFileStamps.sh>
 * Last time was modified by <StampedSourceFile.kt>
 *
 * Created: <02/07/2020, 11:27:00 PM>
 * Modified: <05/07/2020, 11:28:52 PM>
 * Version: <180>
 */

package worder.insert.view

import javafx.geometry.HorizontalDirection
import javafx.geometry.Pos
import javafx.scene.Parent
import javafx.scene.layout.VBox
import javafx.stage.FileChooser.ExtensionFilter
import tornadofx.View
import tornadofx.addClass
import tornadofx.borderpane
import tornadofx.box
import tornadofx.button
import tornadofx.hbox
import tornadofx.label
import tornadofx.onChange
import tornadofx.paddingAll
import tornadofx.replaceChildren
import tornadofx.separator
import tornadofx.stackpane
import tornadofx.style
import tornadofx.vbox
import worder.core.styles.WorderDefaultStyles
import worder.core.view.DragAndDropFragment
import worder.core.view.worderStatusLabel
import worder.database.DatabaseController
import worder.database.DatabaseEventListener
import worder.database.model.WorderDB
import worder.database.view.NoConnectionFragment
import worder.insert.InsertController
import worder.insert.model.InsertUnit
import worder.tornadofx.addAll
import java.awt.Color
import java.io.File

class InsertView : View("Insert"), DatabaseEventListener {
    private val insertUploadedView: InsertUploadedView by inject()
    private val insertController: InsertController by inject()
    private val notConnectedFragment = find<NoConnectionFragment>()
    private val notUploadedFragment = find<DragAndDropFragment>(
            "text" to "Drag one or more plain files here to process them",
            "windowTitle" to "Inserter Files Selection",
            "extensionFilter" to ExtensionFilter("Text Files (*.txt)", "*.txt"),
            "action" to { files: List<File> -> insertController.generateInsertModel(files) },
            "allowMultiselect" to true
    )

    override val root: Parent = stackpane()


    init {
        find<DatabaseController>().subscribeAndRaise(this)
    }


    override fun onDatabaseConnection(db: WorderDB) = toNotUploadedState()

    override fun onDatabaseDisconnection() = toNotConnectedState()


    fun toNotConnectedState() = root.replaceChildren(notConnectedFragment.root)

    fun toNotUploadedState() = root.replaceChildren(notUploadedFragment.root)

    fun toUploadedState() = root.replaceChildren(insertUploadedView.root)
}

class InsertUploadedView : View() {
    private val insertController: InsertController by inject()
    private val insertModelUI = vbox(spacing = 15, alignment = Pos.BASELINE_CENTER)
    private val uncommittedUnitsUI: VBox = vbox(spacing = 15)
    private val committedUnitsUI: VBox = vbox(spacing = 15)


    override val root: Parent = borderpane {
        paddingAll = 15

        left = find<InsertUnitsContainerFragment>(
                "containerTitle" to "UNCOMMITTED UNITS",
                "units" to uncommittedUnitsUI,
                "direction" to HorizontalDirection.LEFT
        ).root

        center = insertModelUI

        right = find<InsertUnitsContainerFragment>(
                "containerTitle" to "COMMITTED UNITS",
                "units" to committedUnitsUI,
                "direction" to HorizontalDirection.RIGHT
        ).root

//        children.style {
//            borderColor += box(Color.GRAY)
//        }
    }


    override fun onDock() {
        val insertModel = insertController.currentInsertModel!!

        uncommittedUnitsUI.addAll(
                insertModel.uncommittedUnits
                        .map { find<InsertUnitFragment>("unit" to it) }
                        .onEach {
                            it.unit.statusProperty.onChange { status ->
                                if (status == InsertUnit.InsertUnitStatus.COMMITTED)
                                    committedUnitsUI.add(it)
                            }
                        }
        )

        insertModelUI.apply {
            addClass(WorderDefaultStyles.insertModel)

            label("INSERT MODEL")
            worderStatusLabel(insertModel.modelStatusProperty)

            hbox {
                isFillWidth = false
                with(insertModel.observableStats) {
                    vbox(alignment = Pos.BASELINE_RIGHT) {
                        label("${generatedUnitsProperty.name}: ")
                        label("${uncommittedUnitsProperty.name}: ")
                        label("${committedUnitsProperty.name}: ")
                        label("${excludedUnitsProperty.name}: ")
                        label("${actionNeededUnitsProperty.name}: ")

                        separator()

                        label("${totalValidWordsProperty.name}: ")
                        label("${totalInvalidWordsProperty.name}: ")

                        separator()

                        label("${totalProcessedProperty.name}: ")
                        label("${insertedProperty.name}: ")
                        label("${resetProperty.name}: ")
                    }

                    vbox(alignment = Pos.BASELINE_LEFT) {
                        label(generatedUnitsProperty)
                        label(uncommittedUnitsProperty)
                        label(committedUnitsProperty)
                        label(excludedUnitsProperty)
                        label(actionNeededUnitsProperty)

                        separator()

                        label(totalValidWordsProperty)
                        label(totalInvalidWordsProperty)

                        separator()

                        label(totalProcessedProperty)
                        label(insertedProperty)
                        label(resetProperty)
                    }
                }
            }

            hbox(spacing = 15) {
                button("<<  Reset This Model")
                button("Commit All Units  >>")
            }
 

            children.style { borderColor += box(javafx.scene.paint.Color.GRAY) }
        }
    }
}
