/**
 * Stamp was generated by <generateFileStamps.sh>
 * Last time was modified by <generateFileStamps.sh>
 *
 * Created: <7/2/20, 11:27 PM>
 * Modified: <7/2/20, 11:50 PM>
 * Version: <1>
 */

package worder.core.model

import javafx.beans.property.ReadOnlyMapProperty

interface ObservableStats {
    val origin: String

    val asMapProperty: ReadOnlyMapProperty<String, Any?>
    val asMap: Map<String, Any?>

    val asTitledMapProperty: ReadOnlyMapProperty<String, Any?>
    val asTitledMap: Map<String, Any?>
}
