/**
 * Stamp was generated by <generateFileStamps.sh>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <WorderStatus.kt>
 * Created: <02/07/2020, 11:27:00 PM>
 * Modified: <20/07/2020, 11:23:20 PM>
 * Version: <4>
 */

package worder.core.model

import javafx.scene.paint.Paint

interface WorderStatus {
    val description: String
    val color: Paint
}
