/**
 * Stamp was generated by <generateFileStamps.sh>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <UpdateModel.kt>
 * Created: <02/07/2020, 11:27:00 PM>
 * Modified: <20/07/2020, 11:22:07 PM>
 * Version: <4>
 */

package worder.update.model

import worder.database.model.WorderUpdateDB

interface UpdateModel : Iterable<WordBlock> {
    val uncommittedBlocks: List<WordBlock>
    val requesters: List<Requester>
    var selectOrder: WorderUpdateDB.SelectOrder

    suspend fun commitAllBlocks()
}
