/**
 * Stamp was generated by <generateFileStamps.sh>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <WordsPipeline.kt>
 * Created: <02/07/2020, 11:27:00 PM>
 * Modified: <22/07/2020, 06:41:15 PM>
 * Version: <5>
 */

package worder.update.model

import worder.database.model.WorderUpdateDB

interface WordsPipeline : Iterable<WordBlock> {
    val uncommittedBlocks: List<WordBlock>
    val usedRequesters: List<Requester>
    var selectOrder: WorderUpdateDB.SelectOrder

    suspend fun commitAllBlocks()
}
