/**
 * Stamp was generated by <generateFileStamps.sh>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <WordBlock.kt>
 * Created: <02/07/2020, 11:27:00 PM>
 * Modified: <24/07/2020, 11:08:53 PM>
 * Version: <7>
 */

package worder.update.model

import javafx.beans.property.ReadOnlyProperty
import javafx.scene.paint.Color
import worder.core.model.WorderStatus
import worder.database.model.DatabaseWord

interface WordBlock {
    val id: String
    val originalWord: DatabaseWord

    val definitions: List<String>
    val examples: List<String>
    val translations: List<String>
    val transcriptions: List<String>

    val statusProperty: ReadOnlyProperty<WordBlockStatus>
    var status: WordBlockStatus

    val resolutionProperty: ReadOnlyProperty<WordBlockResolution>
    val resolution: WordBlockResolution


    suspend fun commit()

    fun update(
            primaryDefinition: String,
            secondaryDefinition: String?,
            transcription: String,
            examples: List<String>
    )

    fun remove()
    fun learn()
    fun skip()


    enum class WordBlockStatus(override val description: String, override val color: Color) : WorderStatus {
        RESOLUTION_NEEDED("User's action is needed to define a resolution", Color.RED),
        READY_TO_COMMIT("Resolution has been received, but still can be changed", Color.ORANGE),
        COMMITTED("Block has been committed to database, its resolution can NOT be changed", Color.DIMGRAY)
    }

    enum class WordBlockResolution {
        NO_RESOLUTION, SKIPPED, REMOVED, LEARNED, UPDATED
    }
}
