/**
 * Stamp was generated by <generateFileStamps.sh>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <CollectionsExt.kt>
 * Created: <02/07/2020, 11:27:00 PM>
 * Modified: <30/07/2020, 10:49:54 PM>
 * Version: <5>
 */

package worder.gui.tornadofx

import javafx.collections.FXCollections
import javafx.collections.ObservableMap
import javafx.collections.ObservableSet
import java.util.*
import kotlin.collections.HashMap
import kotlin.collections.LinkedHashSet

fun <K, V> observableMapOf(): ObservableMap<K, V> = FXCollections.observableMap(LinkedHashMap())

fun <K, V> observableHashMapOf(): ObservableMap<K, V> = FXCollections.observableMap(HashMap())

fun <E> observableLinkedHashSet(): ObservableSet<E> = FXCollections.observableSet(LinkedHashSet())
