/**
 * Stamp was generated by <generateFileStamps.sh>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <SimpleDatabaseStats.kt>
 * Created: <02/07/2020, 11:27:00 PM>
 * Modified: <17/02/2021, 05:03:06 PM>
 * Version: <12>
 */

package worder.gui.database.model.impl

import worder.gui.core.model.BaseObservableStats
import worder.gui.database.model.ObservableInserterStats
import worder.gui.database.model.ObservableUpdaterStats
import worder.gui.database.model.ObservableWorderSummaryStats
import worder.gui.database.model.ObservableWorderTrackStats

open class SimpleWorderTrackStats(
        origin: String = "Worder App Tracker",

        totalAffected: Int = 0,
        totalInserted: Int = 0,
        totalReset: Int = 0,
        totalUpdated: Int = 0
) : BaseObservableStats(origin), ObservableWorderTrackStats {
    override var totalAffected: Int by bindThroughValue(initValue = totalAffected, title = "Total affected")
    override var totalInserted: Int by bindThroughValue(initValue = totalInserted, title = "Total inserted")
    override var totalReset: Int by bindThroughValue(initValue = totalReset, title = "Total reset")
    override var totalUpdated: Int by bindThroughValue(initValue = totalUpdated, title = "Total updated")
}

open class SimpleWorderSummaryStats(
        origin: String = "Database Summary",

        totalAmount: Int = 0,
        unlearned: Int = 0,
        learned: Int = 0,
        toUpdate: Int = 0,
        readyToTrain: Int = 0
) : BaseObservableStats(origin), ObservableWorderSummaryStats {
    override var totalAmount: Int by bindThroughValue(initValue = totalAmount, title = "Total amount")
    override var unlearned: Int by bindThroughValue(initValue = unlearned, title = "Unlearned")
    override var learned: Int by bindThroughValue(initValue = learned, title = "Learned")
    override var toUpdate: Int by bindThroughValue(initValue = toUpdate, title = "To update")
    override var readyToTrain: Int by bindThroughValue(initValue = readyToTrain, title = "Ready to train")
}

open class SimpleUpdaterStats(
        origin: String = "Updater Session",

        totalProcessed: Int = 0,
        removed: Int = 0,
        updated: Int = 0,
        skipped: Int = 0,
        learned: Int = 0
) : BaseObservableStats(origin), ObservableUpdaterStats {
    override var totalProcessed: Int by bindThroughValue(initValue = totalProcessed, title = "Total processed")
    override var removed: Int by bindThroughValue(initValue = removed, title = "Removed")
    override var updated: Int by bindThroughValue(initValue = updated, title = "Updated")
    override var skipped: Int by bindThroughValue(initValue = skipped, title = "Skipped")
    override var learned: Int by bindThroughValue(initValue = learned, title = "Learned")

}

open class SimpleInserterStats(
        origin: String = "Inserter Session",

        totalProcessed: Int = 0,
        inserted: Int = 0,
        reset: Int = 0
) : BaseObservableStats(origin), ObservableInserterStats {
    override var totalProcessed: Int by bindThroughValue(initValue = totalProcessed, title = "Total processed")
    override var inserted: Int by bindThroughValue(initValue = inserted, title = "Inserted")
    override var reset: Int by bindThroughValue(initValue = reset, title = "Reset")
}
