/**
 * Stamp was generated by <generateFileStamps.sh>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <DatabaseEventProducer.kt>
 * Created: <02/07/2020, 11:27:00 PM>
 * Modified: <04/08/2020, 07:11:08 PM>
 * Version: <5>
 */

package worder.gui.database

import worder.gui.database.DatabaseEventListener

interface DatabaseEventProducer {
    fun subscribe(eventListener: DatabaseEventListener)
    fun subscribeAndRaise(eventListener: DatabaseEventListener)
}
