/**
 * Stamp was generated by <generateFileStamps.sh>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <DatabaseEventProducer.kt>
 * Created: <02/07/2020, 11:27:00 PM>
 * Modified: <06/07/2020, 07:25:08 PM>
 * Version: <4>
 */

package worder.gui.database

import worder.gui.database.DatabaseEventListener

interface DatabaseEventProducer {
    fun subscribe(eventListener: DatabaseEventListener)
    fun subscribeAndRaise(eventListener: DatabaseEventListener)
}
