/**
 * Stamp was generated by <generateFileStamps.sh>
 * Last time was modified by <generateFileStamps.sh>
 *
 * Created: <7/2/20, 11:27 PM>
 * Modified: <7/2/20, 11:50 PM>
 * Version: <1>
 */

package worder.database.model

import worder.core.model.Word

class DatabaseWord(
        name: String,
        transcription: String?,

        val rate: Int,
        val register: Long,
        val lastModification: Long,
        val lastRateModification: Long,
        val lastTraining: Int,

        val translations: Set<String>,
        val examples: Set<String>
) : Word(name, transcription)

class UpdatedWord(
        name: String,
        transcription: String?,

        val primaryDefinition: String,
        val secondaryDefinition: String?,
        val examples: Set<String>
) : Word(name, transcription)
