/**
 * Stamp was generated by <generateFileStamps.sh>
 * Last time was modified by <generateFileStamps.sh>
 *
 * Created: <7/2/20, 11:27 PM>
 * Modified: <7/2/20, 11:50 PM>
 * Version: <1>
 */

package worder.database.model

interface WorderDB {
    val observableTrackStats: ObservableWorderTrackStats
    val observableSummaryStats: ObservableWorderSummaryStats


    val inserter: WorderInsertDB
        get() = error("Operation is not supported!")

    val updater: WorderUpdateDB
        get() = error("Operation is not supported!")
}
