/**
 * Stamp was generated by <generateFileStamps.sh>
 * Last time was modified by <generateFileStamps.sh>
 *
 * Created: <7/2/20, 11:27 PM>
 * Modified: <7/2/20, 11:50 PM>
 * Version: <1>
 */

package worder.database.model

import worder.core.model.BareWord

interface WorderUpdateDB {
    val observableUpdaterStats: ObservableUpdaterStats


    suspend fun hasNextWord(): Boolean

    suspend fun getNextWord(order: SelectOrder): DatabaseWord

    suspend fun updateWord(updatedWord: UpdatedWord)

    suspend fun removeWord(bareWord: BareWord)

    suspend fun setAsSkipped(bareWord: BareWord)

    suspend fun setAsLearned(bareWord: BareWord)


    enum class SelectOrder {
        ASC, DESC, RANDOM
    }
}
