/**
 * Stamp was generated by <generateFileStamps.sh>
 * Last time was modified by <generateFileStamps.sh>
 *
 * Created: <7/2/20, 11:27 PM>
 * Modified: <7/2/20, 11:50 PM>
 * Version: <1>
 */

package worder.database.model

import worder.core.model.BareWord

interface WorderInsertDB {
    val observableInserterStats: ObservableInserterStats

    suspend fun resolveWords(bareWords: Collection<BareWord>): Map<BareWord, ResolveRes>

    enum class ResolveRes {
        INSERTED, RESET
    }
}
