/**
 * Stamp was generated by <generateFileStamps.sh>
 * Last time was modified by <StampedSourceFile.kt>
 *
 * Created: <02/07/2020, 11:27:00 PM>
 * Modified: <04/07/2020, 10:57:25 PM>
 * Version: <2>
 */

package worder.database.model

interface WorderDB {
    val observableTrackStats: ObservableWorderTrackStats
    val observableSummaryStats: ObservableWorderSummaryStats


    val inserter: WorderInsertDB
        get() = error("Operation is not supported!")

    val updater: WorderUpdateDB
        get() = error("Operation is not supported!")
}
