/**
 * Stamp was generated by <generateFileStamps.sh>
 * Last time was modified by <StampedSourceFile.kt>
 *
 * Created: <02/07/2020, 11:27:00 PM>
 * Modified: <04/07/2020, 10:57:25 PM>
 * Version: <2>
 */

package worder.database.model

import worder.core.model.BareWord

interface WorderInsertDB {
    val observableInserterStats: ObservableInserterStats

    suspend fun resolveWords(bareWords: Collection<BareWord>): Map<BareWord, ResolveRes>

    enum class ResolveRes {
        INSERTED, RESET
    }
}
