/**
 * Stamp was generated by <StampedSourceFile.kt>
 * Last time was modified by <StampedSourceFile.kt>
 *
 * Created: <7/4/20, 5:02 PM>
 * Modified: <7/4/20, 5:02 PM>
 * Version: <1>
 */

package worder.kotest

import io.kotest.core.spec.style.ShouldSpec

class KotestCodeCompletionTest : ShouldSpec({
    should("auto complete code with suggestions from Kotest API") {
//        listOf("").shoul
    }
})
