/**
 * Stamp was generated by <StampedSourceFile.kt>
 * Last time was modified by <StampedSourceFile.kt>
 *
 * Created: <04/07/2020, 05:02:00 PM>
 * Modified: <04/07/2020, 10:57:25 PM>
 * Version: <2>
 */

package worder.kotest

import io.kotest.core.spec.style.ShouldSpec

/**
 * Simple example for the IDE.Completion Bug
 * https://youtrack.jetbrains.com/issue/KT-40015
 */

class KotestCodeCompletionTest : ShouldSpec({
    should("auto complete code with suggestions from Kotest API") {
//        listOf("").shoul
    }
})
