/**
 * Stamp was generated by <StampedFile.kt>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <MapBasedStatsFragment.kt>
 * Created: <10/07/2020, 09:03:31 PM>
 * Modified: <16/07/2020, 09:35:08 PM>
 * Version: <10>
 */

package worder.core.view

import javafx.collections.ObservableMap
import javafx.geometry.Pos
import tornadofx.Fragment
import tornadofx.addClass
import tornadofx.hbox
import tornadofx.label
import tornadofx.paddingBottom
import tornadofx.vbox
import worder.core.styles.WorderDefaultStyles
import worder.tornadofx.bindChildren

class MapBasedStatsFragment : Fragment() {
    private val blockTitle: String by param()
    private val statsProperties: ObservableMap<String, Any?> by param()
    private val nameMutators: Map<String, String.() -> String> by param(emptyMap())
    private val valueMutators: Map<String, Any?.() -> String> by param(emptyMap())


    override val root = vbox {
        label(blockTitle) {
            paddingBottom = 15
        }

        hbox {
            vbox(alignment = Pos.BASELINE_RIGHT).bindChildren(this@MapBasedStatsFragment.statsProperties) { name, _ ->
                label("${nameMutators[name]?.invoke(name) ?: name}: ")
            }

            vbox(alignment = Pos.BASELINE_LEFT).bindChildren(this@MapBasedStatsFragment.statsProperties) { name, value ->
                label("${valueMutators[name]?.invoke(value) ?: value}")
            }
        }

        addClass(WorderDefaultStyles.statsBlock)
    }
}
