/**
 * Stamp was generated by <generateFileStamps.sh>
 * Last time was modified by <StampedSourceFile.kt>
 *
 * Created: <7/2/20, 11:27 PM>
 * Modified: <7/4/20, 8:54 PM>
 * Version: <3>
 */

package worder.core.view

import javafx.geometry.Pos
import tornadofx.Fragment
import tornadofx.addClass
import tornadofx.hbox
import tornadofx.label
import tornadofx.paddingBottom
import tornadofx.vbox
import worder.core.model.ObservableStats
import worder.core.styles.WorderDefaultStyles
import worder.tornadofx.bindChildren

class ObservableStatsFragment : Fragment() {
    private val observableStats: ObservableStats by param()
    private val titleMutators: Map<String, String.() -> String> by param(emptyMap())
    private val valueMutators: Map<String, Any?.() -> String> by param(emptyMap())

    override val root = vbox {
        label(observableStats.origin) {
            paddingBottom = 15
        }

        hbox {
            vbox(alignment = Pos.BASELINE_RIGHT).bindChildren(observableStats.asTitledMapProperty) { title, _ ->
                label("${titleMutators[title]?.invoke(title) ?: title}: ")
            }

            vbox(alignment = Pos.BASELINE_LEFT).bindChildren(observableStats.asTitledMapProperty) { title, value ->
                label("${valueMutators[title]?.invoke(value) ?: value}")
            }
        }

        addClass(WorderDefaultStyles.statBlock)
    }
}
