/**
 * Stamp was generated by <generateFileStamps.sh>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <TornadofxExt.kt>
 * Created: <02/07/2020, 11:27:00 PM>
 * Modified: <16/07/2020, 11:40:53 PM>
 * Version: <15>
 */

package worder.core.view

import javafx.beans.property.ReadOnlyProperty
import javafx.beans.value.ObservableValue
import javafx.event.EventTarget
import javafx.scene.control.Label
import tornadofx.Component
import tornadofx.attachTo
import tornadofx.onChange
import tornadofx.stringBinding
import tornadofx.tooltip
import worder.core.model.ObservableStats
import worder.core.model.Status

inline fun EventTarget.worderStatusLabel(
        status: ObservableValue<out Status>,
        op: Label.() -> Unit = {}
) = Label().attachTo(this, op) { label ->
    label.textProperty().bind(status.stringBinding { "$it" })

    label.tooltip(status.value.description)
    label.textFill = status.value.color

    status.onChange {
        label.tooltip(status.value.description)
        label.textFill = status.value.color
    }
}

fun Component.observableStats(
        stats: ObservableStats,
        nameMutators: Map<String, String.() -> String> = emptyMap(),
        valueMutators: Map<String, Any?.() -> String> = emptyMap()
) = find<MapBasedStatsFragment>(
        "blockTitle" to stats.origin,
        "statsProperties" to stats.asTitledMapProperty,
        "nameMutators" to nameMutators,
        "valueMutators" to valueMutators
)

fun Component.observableStats(
        statsProperties: List<ReadOnlyProperty<*>>,
        blockTitle: String? = null,
        nameMutators: Map<String, String.() -> String> = emptyMap(),
        valueMutators: Map<String, Any?.() -> String> = emptyMap()
) = find<ListBasedStatsFragment>(
        "blockTitle" to blockTitle,
        "statsProperties" to statsProperties,
        "nameMutators" to nameMutators,
        "valueMutators" to valueMutators
)
