/**
 * Stamp was generated by <StampedSourceFile.kt>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <BatchUnitsContainerFragment.kt>
 * Created: <05/07/2020, 06:50:42 PM>
 * Modified: <01/08/2020, 09:55:33 PM>
 * Version: <93>
 */

package worder.insert.ui

import javafx.collections.ObservableList
import javafx.geometry.HorizontalDirection
import javafx.geometry.Orientation
import javafx.geometry.Pos
import javafx.scene.Parent
import javafx.scene.control.ScrollBar
import javafx.scene.control.ScrollPane
import javafx.scene.layout.HBox
import javafx.scene.layout.Region
import javafx.scene.layout.VBox
import tornadofx.Fragment
import tornadofx.bindComponents
import tornadofx.hbox
import tornadofx.imageview
import tornadofx.label
import tornadofx.onChange
import tornadofx.paddingHorizontal
import tornadofx.paddingLeft
import tornadofx.paddingRight
import tornadofx.px
import tornadofx.scrollpane
import tornadofx.style
import tornadofx.vbox
import tornadofx.visibleWhen
import worder.insert.model.BatchUnit

class BatchUnitsContainerFragment : Fragment() {
    private val units: ObservableList<BatchUnit> by param()
    private val direction: HorizontalDirection by param()
    private val scrollBarUI: ScrollBar = ScrollBar().apply {
        orientation = Orientation.VERTICAL
        visibleWhen {
            visibleAmountProperty().lessThan(1.0)
        }
    }
    private val unitsUI: VBox = vbox(spacing = 20) {
        bindComponents(units) { unit ->
            find<BatchUnitFragment>("unit" to unit)
        }
    }


    override val root = hbox {
        setMaxSize(Region.USE_PREF_SIZE, Region.USE_PREF_SIZE)

        if (direction == HorizontalDirection.LEFT) {
            paddingRight = scrollBarUI.width
            add(scrollBarUI)
        }

        val scrollPane = scrollpane {
            content = if (units.isEmpty()) find<EmptyUnitsContainer>().root else unitsUI
            vbarPolicy = ScrollPane.ScrollBarPolicy.NEVER
            hbarPolicy = ScrollPane.ScrollBarPolicy.NEVER
            alignment = Pos.CENTER

            when(direction) {
                HorizontalDirection.LEFT -> paddingLeft = 15
                HorizontalDirection.RIGHT -> paddingRight = 15
            }

            scrollBarUI.apply {
                minProperty().bind(vminProperty())
                maxProperty().bind(vmaxProperty())
                visibleAmountProperty().bind(heightProperty().divide(unitsUI.heightProperty()))
                vvalueProperty().bindBidirectional(valueProperty())
            }
        }

        if (direction == HorizontalDirection.RIGHT) {
            paddingLeft = scrollBarUI.width
            add(scrollBarUI)
        }

        unitsUI.children.onChange {
            when (it.list.size) {
                0 -> scrollPane.content = find<EmptyUnitsContainer>().root
                1 -> scrollPane.content = unitsUI
            }
        }
    }


    class EmptyUnitsContainer : Fragment() {
        override val root: Parent = vbox(spacing = 15) {
            imageview("/images/empty-box.png")
            label("NO UNITS HERE :(").style { fontSize = 18.px }
        }
    }
}
