/**
 * Stamp was generated by <StampedFile.kt>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <JHyperlink.java>
 * Created: <27/10/2020, 05:20:42 PM>
 * Modified: <14/11/2020, 10:58:35 PM>
 * Version: <588>
 */

package worder.launcher.ui.impl.swing;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

/**
 * A hyperlink component that is based on JLabel.
 * @author www.codejava.net
 */
public class JHyperlink extends JLabel {
    private final String html = "<html><a href=''>%s</a></html>";
    private final String url;

    public JHyperlink(String text, String url, Icon icon, int horizontalAlignment) {
        super(text, icon, horizontalAlignment);
        this.url = url;

        setForeground(new Color(93, 188, 210));
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                setText(String.format(html, text));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                setText(text);
            }

            @Override
            public void mouseClicked(MouseEvent e) {
                try {
                    Desktop.getDesktop().browse(new URI(JHyperlink.this.url));
                } catch (IOException | URISyntaxException e1) {
                    JOptionPane.showMessageDialog(JHyperlink.this,
                            "Could not open the hyperlink. Error: " + e1.getMessage(),
                            "Error",
                            JOptionPane.ERROR_MESSAGE
                    );
                }
            }
        });
    }
}
