/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package worder

import tornadofx.App
import tornadofx.View
import tornadofx.vbox

class MainScene: App(MyView::class)

class MyView: View() {
    override val root = vbox {
    }
}
