/**
 * Stamp was generated by <StampedFile.kt>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <DefaultInsertModelTest.kt>
 * Created: <17/07/2020, 04:21:45 PM>
 * Modified: <17/07/2020, 04:21:45 PM>
 * Version: <1>
 */

package worder.insert.model.implementations

import io.kotest.core.spec.style.ShouldSpec
import worder.core.AppEntry
import java.nio.file.Files
import java.nio.file.Path

class DefaultInsertModelTest : ShouldSpec({
    @Suppress("BlockingMethodInNonBlockingContext")
    should("perform concurrent commit") {


//        val times = 100_000
//        val stats = object : BaseObservableStats("Testing Stats Object") {
//            var counter: Int by bindToStats(0)
//        }
//
//        runBlocking(Dispatchers.Default) {
//            repeat(times) {
//                launch { stats.counter++ }
//            }
//        }
//
//        stats.counter shouldNotBe times
//        stats.counter = 0
//
//        runBlocking(Dispatchers.Default) {
//            repeat(times) {
//                launch { stats.applyWithMainUI { counter++ } }
//            }
//        }
//
//        stats.counter shouldBe times
    }
})