/**
 * Stamp was generated by <generateFileStamps.sh>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <DatabaseStats.kt>
 * Created: <02/07/2020, 11:27:00 PM>
 * Modified: <17/02/2021, 05:03:06 PM>
 * Version: <6>
 */

package worder.gui.database.model

import worder.gui.core.model.ObservableStats

interface ObservableWorderSummaryStats : ObservableStats {
    val totalAmount: Int
    val unlearned: Int
    val learned: Int
    val toUpdate: Int
    val readyToTrain: Int
}

interface ObservableWorderTrackStats : ObservableStats {
    val totalInserted: Int
    val totalReset: Int
    val totalUpdated: Int
    val totalAffected: Int
}

interface ObservableUpdaterStats : ObservableStats {
    val totalProcessed: Int
    val removed: Int
    val updated: Int
    val skipped: Int
    val learned: Int
}

interface ObservableInserterStats : ObservableStats {
    val totalProcessed: Int
    val inserted: Int
    val reset: Int
}
