/**
 * Stamp was generated by <StampedFile.kt>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <Action.java>
 * Created: <05/11/2020, 08:36:34 PM>
 * Modified: <08/11/2020, 06:24:23 PM>
 * Version: <66>
 */

package worder.launcher.model;

@FunctionalInterface
public interface Action {
    void execute();
}
