/**
 * Stamp was generated by <StampedFile.kt>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <WorderRunner.java>
 * Created: <05/11/2020, 08:36:34 PM>
 * Modified: <07/11/2020, 02:24:33 PM>
 * Version: <27>
 */

package worder.launcher.model;

import worder.launcher.ui.UiHandler;

public class WorderRunner {
    public WorderRunner(UiHandler uiHandler, String worderHomeCatalog) {

    }
}
