/**
 * Stamp was generated by <generateFileStamps.sh>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <InsertController.kt>
 * Created: <02/07/2020, 11:27:00 PM>
 * Modified: <20/07/2020, 11:23:03 PM>
 * Version: <8>
 */

package worder.insert

import tornadofx.Controller
import worder.database.DatabaseController
import worder.insert.model.impl.DefaultInsertModel
import java.io.File

class InsertController : Controller() {
    private val insertView: InsertView by inject()
    private val databaseController: DatabaseController by inject()


    fun generateInsertModel(files: List<File>) {
        val insertModel = DefaultInsertModel.createInstance(databaseController.db!!.inserter, files)
        insertView.toUploadedState(insertModel)
    }

    fun releaseInsertModel() {
        insertView.toNotUploadedState()
    }
}
