/**
 * Stamp was generated by <StampedFile.kt>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <UpdateModelFragment.kt>
 * Created: <20/07/2020, 06:26:55 PM>
 * Modified: <20/07/2020, 06:26:55 PM>
 * Version: <1>
 */

package worder.update.ui

import javafx.scene.Parent
import tornadofx.Fragment
import tornadofx.borderpane
import worder.database.model.WorderUpdateDB

class UpdateModelFragment : Fragment() {
    private val db: WorderUpdateDB by param()


    override val root: Parent = borderpane {

    }
}
