/**
 * Stamp was generated by <StampedFile.kt>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <DevRequester.kt>
 * Created: <24/07/2020, 07:45:55 PM>
 * Modified: <24/07/2020, 09:52:09 PM>
 * Version: <7>
 */

package worder.update.model.impl.requesters

import javafx.beans.property.ReadOnlyProperty
import javafx.beans.property.SimpleBooleanProperty
import worder.core.model.BareWord
import worder.update.model.DefinitionRequester
import worder.update.model.ExampleRequester
import worder.update.model.ObservableRequesterStats
import worder.update.model.Requester
import worder.update.model.TranscriptionRequester
import worder.update.model.TranslationRequester
import worder.update.model.impl.SimpleRequesterStats
import worder.update.model.impl.WebsiteRequesterDecorator

class DevRequester : DefinitionRequester, ExampleRequester, TranscriptionRequester, TranslationRequester {
    companion object {
        val instance: Requester by lazy {
            object : WebsiteRequesterDecorator(DevRequester()), DefinitionRequester, ExampleRequester, TranscriptionRequester, TranslationRequester {}
        }
    }


    override val isBusy: Boolean = false
    override val isBusyProperty: ReadOnlyProperty<Boolean> = SimpleBooleanProperty()
    override val observableStats: ObservableRequesterStats = SimpleRequesterStats("Dev Requester")
    override val definitions: List<String> = listOf(
            "a place regarded in various religions as a spiritual realm of evil and suffering.",
            "used to express annoyance or surprise or for emphasis.",
            "used to express annoyance or surprise or for emphasis."
    )
    override val examples: List<String> = listOf(
            "hell, no, we were all married",
            "I've been through hell"
    )
    override val translations: List<String> = listOf(
            "ад",
            "преисподня",
            "притон",
            "игорный дом"
    )
    override val transcriptions: List<String> = listOf(
            "hel"
    )


    override suspend fun requestWord(word: BareWord) {}
}