/**
 * Stamp was generated by <generateFileStamps.sh>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <DatabaseDashboardView.kt>
 * Created: <02/07/2020, 11:27:00 PM>
 * Modified: <04/08/2020, 07:11:08 PM>
 * Version: <26>
 */

package worder.gui.core

import javafx.geometry.Pos
import tornadofx.View
import tornadofx.hbox
import tornadofx.paddingVertical
import worder.gui.database.DatabaseController
import worder.gui.database.DatabaseEventListener
import worder.gui.database.model.WorderDB

class DatabaseDashboardView : View(), DatabaseEventListener {
    private val databaseController: DatabaseController by inject()


    override val root = hbox(spacing = 30, alignment = Pos.TOP_CENTER) {
        paddingVertical = 30
    }


    init {
        databaseController.subscribe(this)
    }


    override fun onDatabaseConnection(db: WorderDB) {
        root.apply {
            observableStats(
                    observableStats = databaseController.controllerStats,
                    valueMutators = mapOf("Data source" to { value: Any? -> value.toString().substringAfterLast("/") })
            )

            observableStats(db.observableSummaryStats, commonValueMutator = { (this as Int).formatGrouped() })
            observableStats(db.observableTrackStats, commonValueMutator = { (this as Int).formatGrouped() })
            observableStats(db.inserter.observableInserterStats, commonValueMutator = { (this as Int).formatGrouped() })
            observableStats(db.updater.observableUpdaterStats, commonValueMutator = { (this as Int).formatGrouped() })
        }
    }

    override fun onDatabaseDisconnection() {
        root.children.clear()
    }
}
