/**
 * Stamp was generated by <generateFileStamps.sh>
 * Last time was modified by <generateFileStamps.sh>
 *
 * Created: <7/2/20, 11:27 PM>
 * Modified: <7/2/20, 11:50 PM>
 * Version: <1>
 */

package worder.tornadofx

import javafx.collections.FXCollections
import javafx.collections.ObservableMap
import java.util.*
import kotlin.collections.HashMap

/**
 * Returns a new empty [ObservableMap] that is backed by a LinkedHashMap
 */
fun <K, V> observableMapOf(): ObservableMap<K, V> = FXCollections.observableMap(LinkedHashMap())

/**
 * Returns an empty new [ObservableMap] that is backed by a HashMap
 */
fun <K, V> observableHashMapOf(): ObservableMap<K, V> = FXCollections.observableMap(HashMap())
