/**
 * Stamp was generated by <generateFileStamps.sh>
 * Last time was modified by <StampedSourceFile.kt>
 *
 * Created: <02/07/2020, 11:27:00 PM>
 * Modified: <04/07/2020, 10:57:25 PM>
 * Version: <2>
 */

package worder.tornadofx

import javafx.collections.FXCollections
import javafx.collections.ObservableMap
import java.util.*
import kotlin.collections.HashMap

/**
 * Returns a new empty [ObservableMap] that is backed by a LinkedHashMap
 */
fun <K, V> observableMapOf(): ObservableMap<K, V> = FXCollections.observableMap(LinkedHashMap())

/**
 * Returns an empty new [ObservableMap] that is backed by a HashMap
 */
fun <K, V> observableHashMapOf(): ObservableMap<K, V> = FXCollections.observableMap(HashMap())
