/**
 * Stamp was generated by <generateFileStamps.sh>
 * Last time was modified by <StampedSourceFile.kt>
 *
 * Created: <7/2/20, 11:27 PM>
 * Modified: <7/2/20, 11:55 PM>
 * Version: <2>
 */

package worder.database

interface DatabaseEventProducer {
    fun subscribe(eventListener: DatabaseEventListener)
    fun subscribeAndRaise(eventListener: DatabaseEventListener)
}
