/**
 * Stamp was generated by <generateFileStamps.sh>
 * Last time was modified by <StampedSourceFile.kt>
 *
 * Created: <02/07/2020, 11:27:00 PM>
 * Modified: <04/07/2020, 10:57:25 PM>
 * Version: <2>
 */

package worder.database

import worder.database.model.WorderDB

interface DatabaseEventListener {
    fun onDatabaseConnection(db: WorderDB)
    fun onDatabaseDisconnection()
}
