/**
 * Stamp was generated by <generateFileStamps.sh>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <InsertBatch.kt>
 * Created: <02/07/2020, 11:27:00 PM>
 * Modified: <04/08/2020, 07:11:08 PM>
 * Version: <9>
 */

package worder.gui.insert.model

import javafx.beans.property.ReadOnlyListProperty
import javafx.beans.property.ReadOnlyProperty
import javafx.scene.paint.Color
import worder.gui.core.model.WorderStatus

interface InsertBatch {
    val statusProperty: ReadOnlyProperty<InsertBatchStatus>
    val status: InsertBatchStatus

    val observableStats: ObservableInsertBatchStats

    val readyToCommitUnitsProperty: ReadOnlyListProperty<BatchUnit>
    val readyToCommitUnits: List<BatchUnit>

    val actionNeededUnitsProperty: ReadOnlyListProperty<BatchUnit>
    val actionNeededUnits: List<BatchUnit>

    val excludedUnitsProperty: ReadOnlyListProperty<BatchUnit>
    val excludedUnits: List<BatchUnit>

    val committingUnitsProperty: ReadOnlyListProperty<BatchUnit>
    val committingUnits: List<BatchUnit>

    val committedUnitsProperty: ReadOnlyListProperty<BatchUnit>
    val committedUnits: List<BatchUnit>


    suspend fun commitAllUnits()


    enum class InsertBatchStatus(override val description: String, override val color: Color) : WorderStatus {
        READY_TO_COMMIT("There are units that can be committed", Color.GREEN),
        ACTION_NEEDED("There are only units with ACTION_NEEDED status", Color.RED),
        COMMITTING("Some of the units are committing now", Color.DARKORANGE),
        COMMITTED("All the units have been committed", Color.GREEN),
        FULL_EXCLUDE("All the units have been excluded", Color.DIMGRAY),
        PARTIALLY_COMMITTED("All the units except for excluded ones have been committed", Color.DARKORANGE);
    }
}
