/**
 * Stamp was generated by <generateFileStamps.sh>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <InsertModel.kt>
 * Created: <02/07/2020, 11:27:00 PM>
 * Modified: <06/07/2020, 07:25:08 PM>
 * Version: <3>
 */

package worder.insert.model

import javafx.beans.property.ReadOnlyProperty
import javafx.beans.property.ReadOnlySetProperty
import javafx.scene.paint.Color
import worder.core.model.Status

interface InsertModel {
    val modelStatusProperty: ReadOnlyProperty<InsertModelStatus>
    val modelStatus: InsertModelStatus

    val observableStats: ObservableInsertModelStats

    val uncommittedUnitsProperty: ReadOnlySetProperty<InsertUnit>
    val uncommittedUnits: Set<InsertUnit>

    val committedUnitsProperty: ReadOnlySetProperty<InsertUnit>
    val committedUnits: Set<InsertUnit>


    suspend fun commitAllUnits()


    enum class InsertModelStatus(override val description: String, override val color: Color) : Status {
        READY_TO_COMMIT("There are units that can be committed", Color.GREEN),
        ACTION_NEEDED("There are only units with ACTION_NEEDED status", Color.RED),
        COMMITTING("Some of the units are committing now", Color.DARKORANGE),
        COMMITTED("All the units have been committed", Color.DIMGRAY),
        PARTIALLY_COMMITTED("All the units except for excluded ones have been committed", Color.DIMGRAY);
    }
}
