/**
 * Stamp was generated by <generateFileStamps.sh>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <InsertModel.kt>
 * Created: <02/07/2020, 11:27:00 PM>
 * Modified: <20/07/2020, 11:23:03 PM>
 * Version: <7>
 */

package worder.insert.model

import javafx.beans.property.ReadOnlyListProperty
import javafx.beans.property.ReadOnlyProperty
import javafx.scene.paint.Color
import worder.core.model.WorderStatus

interface InsertModel {
    val modelStatusProperty: ReadOnlyProperty<InsertModelStatus>
    val modelStatus: InsertModelStatus

    val observableStats: ObservableInsertModelStats

    val readyToCommitUnitsProperty: ReadOnlyListProperty<InsertUnit>
    val readyToCommitUnits: List<InsertUnit>

    val actionNeededUnitsProperty: ReadOnlyListProperty<InsertUnit>
    val actionNeededUnits: List<InsertUnit>

    val excludedUnitsProperty: ReadOnlyListProperty<InsertUnit>
    val excludedUnits: List<InsertUnit>

    val committingUnitsProperty: ReadOnlyListProperty<InsertUnit>
    val committingUnits: List<InsertUnit>

    val committedUnitsProperty: ReadOnlyListProperty<InsertUnit>
    val committedUnits: List<InsertUnit>


    suspend fun commitAllUnits()


    enum class InsertModelStatus(override val description: String, override val color: Color) : WorderStatus {
        READY_TO_COMMIT("There are units that can be committed", Color.GREEN),
        ACTION_NEEDED("There are only units with ACTION_NEEDED status", Color.RED),
        COMMITTING("Some of the units are committing now", Color.DARKORANGE),
        COMMITTED("All the units have been committed", Color.GREEN),
        FULL_EXCLUDE("All the units have been excluded", Color.DIMGRAY),
        PARTIALLY_COMMITTED("All the units except for excluded ones have been committed", Color.DARKORANGE);
    }
}
