/**
 * Stamp was generated by <generateFileStamps.sh>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <ObservableInsertModelStats.kt>
 * Created: <02/07/2020, 11:27:00 PM>
 * Modified: <16/07/2020, 10:43:10 PM>
 * Version: <7>
 */

package worder.insert.model

import javafx.beans.property.ReadOnlyIntegerProperty
import worder.core.model.ObservableStats

interface ObservableInsertModelStats : ObservableStats {
    /**
     * Contains stats values related to units / insert progress
     */

    val generatedUnitsProperty: ReadOnlyIntegerProperty
    val generatedUnits: Int

    val readyToCommitUnitsProperty: ReadOnlyIntegerProperty
    val readyToCommitUnits: Int

    val actionNeededUnitsProperty: ReadOnlyIntegerProperty
    val actionNeededUnits: Int

    val excludedUnitsProperty: ReadOnlyIntegerProperty
    val excludedUnits: Int

    val committedUnitsProperty: ReadOnlyIntegerProperty
    val committedUnits: Int


    /**
     * Contains stats values related to uploaded data
     */
    val totalWordsProperty: ReadOnlyIntegerProperty
    val totalWords: Int

    val totalValidWordsProperty: ReadOnlyIntegerProperty
    val totalValidWords: Int

    val totalInvalidWordsProperty: ReadOnlyIntegerProperty
    val totalInvalidWords: Int


    /**
     * Contains stats values related to processed data
     */

    val totalProcessedProperty: ReadOnlyIntegerProperty
    val totalProcessed: Int

    val insertedProperty: ReadOnlyIntegerProperty
    val inserted: Int

    val resetProperty: ReadOnlyIntegerProperty
    val reset: Int
}
