/**
 * Stamp was generated by <generateFileStamps.sh>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <ObservableInsertModelStats.kt>
 * Created: <02/07/2020, 11:27:00 PM>
 * Modified: <06/07/2020, 07:25:08 PM>
 * Version: <4>
 */

package worder.insert.model

import javafx.beans.property.ReadOnlyIntegerProperty
import worder.core.model.ObservableStats

interface ObservableInsertModelStats : ObservableStats {
    /**
     * Contains stats values related to units
     */

    val generatedUnitsProperty: ReadOnlyIntegerProperty
    val generatedUnits: Int

    val uncommittedUnitsProperty: ReadOnlyIntegerProperty
    val uncommittedUnits: Int

    val committedUnitsProperty: ReadOnlyIntegerProperty
    val committedUnits: Int

    val excludedUnitsProperty: ReadOnlyIntegerProperty
    val excludedUnits: Int

    val actionNeededUnitsProperty: ReadOnlyIntegerProperty
    val actionNeededUnits: Int


    /**
     * Contains stats values related to processed files
     */

    val totalValidWordsProperty: ReadOnlyIntegerProperty
    val totalValidWords: Int

    val totalInvalidWordsProperty: ReadOnlyIntegerProperty
    val totalInvalidWords: Int


    /**
     * Contains stats values related to InsertModel itself
     */

    val totalProcessedProperty: ReadOnlyIntegerProperty
    val totalProcessed: Int

    val insertedProperty: ReadOnlyIntegerProperty
    val inserted: Int

    val resetProperty: ReadOnlyIntegerProperty
    val reset: Int
}
