/**
 * Stamp was generated by <StampedFile.kt>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <DarkThemeStyle.kt>
 * Created: <02/08/2020, 04:33:41 PM>
 * Modified: <04/08/2020, 07:11:08 PM>
 * Version: <2>
 */

package worder.gui.core.styles

class DarkThemeStyle
