/**
 * Stamp was generated by <StampedFile.kt>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <FakeRequester.kt>
 * Created: <24/07/2020, 07:45:55 PM>
 * Modified: <11/02/2021, 07:07:59 PM>
 * Version: <24>
 */

package worder.gui.update.model.impl.requesters

import javafx.beans.property.ReadOnlyProperty
import javafx.beans.property.SimpleBooleanProperty
import kotlinx.coroutines.delay
import worder.gui.core.model.BareWord
import worder.gui.update.model.DefinitionRequester
import worder.gui.update.model.ExampleRequester
import worder.gui.update.model.ObservableRequesterStats
import worder.gui.update.model.Requester
import worder.gui.update.model.TranscriptionRequester
import worder.gui.update.model.TranslationRequester
import worder.gui.update.model.impl.SimpleRequesterStats
import worder.gui.update.model.impl.WebsiteRequesterDecorator

class FakeRequester : DefinitionRequester, ExampleRequester, TranscriptionRequester, TranslationRequester {
    companion object {
        val instance: Requester by lazy {
            object : WebsiteRequesterDecorator(FakeRequester()), DefinitionRequester, ExampleRequester, TranscriptionRequester, TranslationRequester {}
        }
    }


    override val isBusy: Boolean = false
    override val isBusyProperty: ReadOnlyProperty<Boolean> = SimpleBooleanProperty()
    override val observableStats: ObservableRequesterStats = SimpleRequesterStats("Fake Requester")
    override val definitions: List<String> = listOf(
            "a place regarded in various religions as a spiritual realm of evil and suffering",
            "used to express annoyance or surprise or for emphasis",
            "In religion and folklore, Hell is an afterlife location in which evil souls are subjected to punitive suffering, often torture as" +
                    "eternal punishment after hell hell hell hell hell hell hell hell hell hell hell hell hell end"
    )
    override val examples: List<String> = listOf(
            "I've been through hell",
            "hell, no, we were all we were all we were all we were we were all we were all we were all we were all we were all we were all all we" +
                    "were all we were all we were all we were all we were all ---------------- hell end"
    )
    override val translations: List<String> = listOf(
            "ад",
            "преисподня",
            "притон",
            "игорный дом0",
            "игорный дом1",
            "игорный дом2",
            "игорный дом3",
            "игорный дом4",
            "игорный дом5",
            "игорный дом6",
            "игорный дом7",
            "игорный дом8",
            "игорный дом9",
            "игорный дом"
    )
    override val transcriptions: List<String> = listOf(
            "hel"
    )


    override suspend fun requestWord(word: BareWord) {
        delay(2000)
    }
}
