/**
 * Stamp was generated by <StampedFile.kt>
 * Last time was modified by <StampedFile.kt>
 *
 * Name: <RemoteIOExchanger.java>
 * Created: <08/11/2020, 01:48:57 PM>
 * Modified: <08/11/2020, 06:24:23 PM>
 * Version: <31>
 */

package worder.launcher.model.impl;

import worder.launcher.model.IOExchanger;

import java.io.IOException;
import java.net.URL;
import java.util.List;
import java.util.stream.Collectors;

public class RemoteIOExchanger implements IOExchanger {
    private final URL root;


    public RemoteIOExchanger(URL root) {
        this.root = root;
    }


    @Override
    public byte[] downloadFile(String path) throws IOException {
        if (path.startsWith("/"))
            throw new IllegalArgumentException("You can't use absolute path here, passed value: " + path);

        var requestedUrl = new URL(root + path);
        var inputStream = requestedUrl.openStream();
        var res = inputStream.readAllBytes();

        inputStream.close();

        return res;
    }

    @Override
    public void uploadFile(String path, byte[] bytes, boolean override) {

    }

    @Override
    public void deleteFile(String path) {

    }

    @Override
    public List<String> listCatalog(String path) throws IOException {
        if (path.startsWith("/"))
            throw new IllegalArgumentException("You can't use absolute path here, passed value: " + path);

        var requestedUrl = new URL(root + path);
        var inputStream = requestedUrl.openStream();
        var res = inputStream.readAllBytes();

        inputStream.close();

        return new String(res).lines().collect(Collectors.toList());
    }
}
